### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ashish-ram** [leal26/AeroPy#1]
Hi Leal, 
I just wanted to contact you by creating this issue on the repo.  I have been looking for an alternative for xfoil for simulation and I think your library can be really useful. However, I could not get this to work yet due to my limited know-how about packages in python. Is it possible for you to help me out. After I clone your repo, how to set it up for use in my code ? I tried to copy it to the pkg directory of my python installation, but I can not import it. 

```
from AeroPy import find_coefficients
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named AeroPy
```

I would really appreciate your time. 

Thanks,
Ashish

**Comment by leal26** [comment]
Hello Ashish,

there are at least three ways of doing it:

   - You define a PYTHONPATH to the AeroPy directory;
   - You run Python in the directory of the AeroPy directory (run python
   from the command line)
   - You place Aeropy in Lib/site-packages for your Python install

This is the kind of question, i.e. not AeroPy specific, that you can easily
find an answer at stackexchange. If you are new to the community, I
recommend creating an account there and using that resource as much as
possible.

Thanks,

Pedro Leal

**Comment by ashish-ram** [comment]
Hi Pedro, 

Thanks a lot for a prompt response. I tried those options in ubuntu, python 2.7.  I did not spend much time debugging it however, sorry for that. It looks related to subprocess. I can run it successfully in Windows perfectly, but I don't want to use windows. 
Regards,
Ashish

**Comment by leal26** [comment]
Hello Ashish,

The error you are getting is because you are trying to run xfoil.exe.
AeroPy uses xfoil.exe which is an executable file. Executable files only
run in Windows OS. Therefore, the current version of AeroPy only works for
Windows. You need the source code for xfoil, which is in Fortran, to make
it work with Linux system. Since I have to use Windows at work, I never did
this.

Pedro Leal
