### ISSUE TITLE
File not found subprocess.py

### ISSUE THREAD

**Issue by J-Massey** [leal26/AeroPy#10]
All i get when i try the example : 
`find_coefficients(airfoil='naca0012'alpha=12.)`
is an output error stating 

> FileNotFoundError: [WinError 2] The system cannot find the file specified

Could you please help me?
Here is a picture:
![image](https://user-images.githubusercontent.com/44616393/47743155-4a8ff480-dc76-11e8-9e6a-d2b7dbe3773d.png)

**Comment by leal26** [comment]
Hello Jonahah. Can you try copying the xfoil.exe to your working directory and see if it works? Please let me know if it does as I will add that to the project description.

**Comment by J-Massey** [comment]
YES!! That works thank you very much that was silly!

**Comment by leal26** [comment]
Glad it worked! Hope you find this library quite useful
