### ISSUE TITLE
xfoil_module not found

### ISSUE THREAD

**Issue by AzamBham** [leal26/AeroPy#12]
Hi Leal,

I recently installed aeropy to use with a problem I've been trying to solve, but I've run into a problem. Every time I try to call the xfoil_module, python states it doesn't exist, like so:
`>>> from aeropy.xfoil_module import find_coefficients
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'aeropy.xfoil_module'`

I'm not sure if the problem is trivial and I'm missing something obvious, but I would really appreciate some help on the matter.

Thank you,
Azam

**Comment by AzamBham** [comment]
Never mind, I figured out the problem

**Comment by pedrosecchi67** [comment]
Hi @ABham2997! Having the same problem over here, haven't yet been able to find out how to solve it... would you mind sharing how you did it?

**Comment by ckanaar** [comment]
Hi @AzamBham 

As I'm experiencing the same issue, I am curious as to how you solved this.

**Comment by leal26** [comment]
@ckanaar this should be indicative that you didn't install the library properly. Did you follow the instructions on the [project description](https://github.com/leal26/AeroPy) and installed the library via 'pip install .'?

**Comment by NasonZ** [comment]
Same issue here, I first installed through anaconda with pip install. Then I uninstalled and re-installed following the project description but I'm still getting the same error.
If anyone know's how to fix this, I'd appreciate the advice.

**Comment by leal26** [comment]
@NasonZ This seems to be a problem not specific to Aeropy ([see here](https://stackoverflow.com/questions/37096055/importing-numpy-results-in-error-even-though-anaconda-says-its-installed)), but from having anaconda or multiple Python versions on the same computer.

I just installed the library utilizing the vanilla version of Python 3.6 (as provided on the Python website) and I can import it. Perhaps you need to start from scratch (no Python libraries installed).
