### ISSUE TITLE
System cannot find file specified

### ISSUE THREAD

**Issue by Gautham-Barathwaj-Padmanaban** [leal26/AeroPy#17]
Hello! 

I was trying to implement the code as shown below.

from aeropy.xfoil_module import find_coefficients
find_coefficients(airfoil='naca0012',alpha=12.)

Whenever I try using any of the modules I get the error [WinError 2] The system cannot find the file specified. Could you explain as to what the problem is?

**Comment by xuliji** [comment]
Hello!Has your problem been solved? I have the same problem as you. Can you teach me how to solve it?
