### ISSUE TITLE
Interest in contributing, possible with unit tests

### ISSUE THREAD

**Issue by rafaellehmkuhl** [leal26/AeroPy#3]
I have interest in contributing to the project, and was thinking in how to.
I didn't see any unit tests on the project. Would you accept unit tests as a first contribution? It would allow me to better understand the code structure and contribute while doing so.

**Comment by rafaellehmkuhl** [comment]
@leal26 I saw that you returned to the project. Will propose the PR them.

**Comment by leal26** [comment]
Hello Rafael,  sorry for the late response (I haven't checked the Issues section for a while). Do you still intend to PR the unit tests? 
Thanks
