### ISSUE TITLE
same values returned regardless of input

### ISSUE THREAD

**Issue by hphilamore** [leal26/AeroPy#6]
I am trying to use the function find_coefficients to find lift and drag coefficients at various attack angles.

Despite entering different foil profiles and angles as input the same output is returned (the only chnage being the input values)

```
Reloaded modules: airfoil_module, AeroPy, aero_module, xfoil_module
{'e': 0.9470954264583017, 'C_D': 0.0002606136938932183, 'C_L': 0.08805832534797597, 'distribution': array([1.        , 0.95215222, 0.89108161, 0.81861249, 0.73638406,
       0.64587692, 0.54845141, 0.4453797 , 0.33786457, 0.22705607]), 'cls': array([0.10798413, 0.10281733, 0.09622267, 0.08839716, 0.07951779,
       0.06974446, 0.05922405, 0.04809394, 0.03648401, 0.02451845]), 'C_Di': 0.0002606136938932183}
1437592.55642
<type 'float'>
NORM
naca0010

OPER
iter
10
MACH 0
PACC
Polar_naca0010_4000_4000

ALFA 40.0000

`QUIT`

```
I can get the desired output from xfoil directly but I would much prefer to use your library as it is much faster and more convenient to use.

Any advice on how to get this running would be much appreciated.

Thanks!

**Comment by leal26** [comment]
Hello,

Not sure if still relevant, but you are probably reading an output file in the wrong directory. If you send me your code, I can probably find the problem.

Thanks
